# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BOSCH', 'BOSCH'), ('VARTA', 'VARTA'), ('FIAMM', 'FIAMM'), ('JENOX', 'JENOX')], max_length=50, verbose_name='Виробник')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Серія')),
                ('image', models.ImageField(blank=True, upload_to='batteries/series')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batteries.BrandName')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SLI', 'CLASIC'), ('AGM', 'AGM'), ('GEL', 'GEL')], default='SLI', max_length=10, verbose_name='Тип акумулятора')),
            ],
        ),
        migrations.CreateModel(
            name='СarBatteries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.PositiveSmallIntegerField(choices=[(12, '12V'), (6, '6V')], default=12, verbose_name='Напруга')),
                ('battery_model', models.CharField(blank=True, max_length=50, verbose_name='Модель')),
                ('cold_cranking_amps', models.PositiveSmallIntegerField(verbose_name='Пусковий струм, А')),
                ('cranking_amps', models.PositiveSmallIntegerField(verbose_name='Ємність, Ah')),
                ('length', models.PositiveSmallIntegerField(blank=True, verbose_name='Довжина, мм')),
                ('width', models.PositiveSmallIntegerField(blank=True, verbose_name='Ширина, мм')),
                ('height', models.PositiveSmallIntegerField(blank=True, verbose_name='Висота, мм')),
                ('positive_terminal_side_right', models.BooleanField(default=True, verbose_name='Полярність права')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Вага, кг')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Ціна, грн')),
                ('image', models.ImageField(blank=True, upload_to='main/battery')),
                ('producer', models.CharField(blank=True, max_length=50, verbose_name='Країна виробник')),
                ('warranty', models.PositiveSmallIntegerField(blank=True, verbose_name='Гарантія, міс.')),
                ('info', models.CharField(blank=True, max_length=50, verbose_name='Примітка')),
                ('battery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batteries.TypeOfBattery')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batteries.BrandName')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductCategory')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batteries.Series')),
            ],
            options={
                'verbose_name_plural': 'Акумулятори',
                'verbose_name': 'Акумулятор',
            },
        ),
    ]
