# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandname',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='typeofbattery',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Тип акумулятора'),
        ),
    ]
