# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0004_auto_20160610_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='сarbatteries',
            name='slug',
            field=models.SlugField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
