# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0006_auto_20160622_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofbattery',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeofbattery',
            name='type_info',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
