# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0009_auto_20160705_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сarbatteries',
            name='image',
            field=models.ImageField(blank=True, default='main/battery/no_image_battery.jpg', upload_to='main/battery'),
        ),
    ]
