# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=32),
            preserve_default=False,
        ),
    ]
